/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.ia.p7.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import uam.ia.p7.main.Conecta4;

/**
 *
 * @author delta9
 */
public class JFrameConecta extends javax.swing.JFrame {
    private final int ARRAYSIZE = 7;
    private JButton[][] buttons;
    private int dificultad;
    private Conecta4 control;
    /**
     * Creates new form JFrameConecta
     */
    public JFrameConecta(Conecta4 app) {
        this.control = app;
        initComponents();
        buttons = new JButton[ARRAYSIZE][ARRAYSIZE];
        initButtons();
        this.dificultad=0;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 7));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Facil");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Intermedio");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Dificil");

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonActionPerformed
        if (evt.getSource() == jRadioButton1){
            this.dificultad = 1;            
        }
        if (evt.getSource() == jRadioButton2){
            this.dificultad = 5;            
        }
        if (evt.getSource() == jRadioButton3){
            this.dificultad = 9;           
        } 
    }//GEN-LAST:event_jRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.clearButtons();
        buttonGroup1.clearSelection();
        this.dificultad = 0;    }//GEN-LAST:event_jButton1ActionPerformed
    private void initButtons(){
    int i;
    for(i=0;i<ARRAYSIZE;i++){
        for(int j=0; j< ARRAYSIZE; j++){
            buttons[i][j] = new JButton("");
            buttons[i][j].setFont(new Font("Dialog", Font.PLAIN, 40));
            buttons[i][j].setOpaque(true); //Para poder mostrar el color del boton
            buttons[i][j].setBackground(Color.WHITE); //inicializa todos blancos
            buttons[i][j].addActionListener(listener);
            jPanel1.add(buttons[i][j]);            
        }
    }
}
    ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int i;
            for(i=0;i<ARRAYSIZE;i++){
                for(int j=0; j< ARRAYSIZE; j++ ){
                    if(e.getSource()== buttons[i][j]){ 
                        if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected() && !jRadioButton3.isSelected()){
                            JOptionPane.showMessageDialog(null, "Elige una dificultad");
                        }
                        else if(i<6 && "".equals(buttons[i+1][j].getText())){
                            JOptionPane.showMessageDialog(null, "Movimiento invalido");
                        }
                        else if("".equals(buttons[i][j].getText()) ){
                            buttons[i][j].setText("O");
                            buttons[i][j].setBackground(Color.ORANGE);
                            control.checkGanador(buttons);                          
                            if(buttons[0][0].isEnabled()){//Si humano no ha ganado
                               control.nextTurn(buttons,dificultad);                         
                            }
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Elige otra casilla");

                    }
                }     
            }
        }
    };
     private void clearButtons(){
        int i;
        for(i=0;i<ARRAYSIZE;i++){
            for(int j=0; j< ARRAYSIZE; j++){
                buttons[i][j].setText("");
                buttons[i][j].setEnabled(true);
                buttons[i][j].setBackground(Color.WHITE);
                
            }
        }
    }     
    public void finJuego(String mensaje){
        for(int i=0; i< ARRAYSIZE; i++){
            for(int j = 0; j<ARRAYSIZE; j++)
                buttons[i][j].setEnabled(false);
        }
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public String[] getButtonsAsString(){
        int k=0;
        String[] tablero = new String[ARRAYSIZE*ARRAYSIZE];
        for(int i=0; i<ARRAYSIZE;i++){
            for(int j = 0; j<ARRAYSIZE;j++){
                tablero[k]= buttons[i][j].getText();
                k++;                
            }

        }
        return tablero;
    }
    public JButton[][] getTablero(){
        return buttons;
    }
    public JButton[][] testNegamax(){
        buttons[6][4].setText("O");
        return buttons;
    }
    public JButton[][] testF_n(){
        JButton[][] temp = new JButton[7][7];    
    for(int i=0;i<ARRAYSIZE;i++){
        for(int j=0; j< ARRAYSIZE; j++){
            temp[i][j] = new JButton("");
            temp[i][j].setFont(new Font("Dialog", Font.PLAIN, 40));
            temp[i][j].setOpaque(true); //Para poder mostrar el color del boton
            temp[i][j].setBackground(Color.WHITE); //inicializa todos blancos
        }
    }
    //Lineas de 4

    temp[6][3].setText("O");
//    temp[1][2].setText("X");
//    temp[2][3].setText("X");
//    temp[3][4].setText("O");
//    
//    //Lineas de 3
//    temp[4][0].setText("X");
//    temp[5][1].setText("X");
//    temp[6][2].setText("X");
//    
//    temp[4][2].setText("X");
//    temp[5][3].setText("X");
//    temp[6][6].setText("X");   
//
//    temp[6][6].setText("X");
//    temp[5][5].setText("X");
//    temp[4][4].setText("X");
//    //lineas de 2
//    temp[0][4].setText("X");
//    temp[1][5].setText("X");
//    
//    temp[1][0].setText("X");
//    temp[2][1].setText("X");

//    temp[2][5].setText("X");
//    temp[1][6].setText("X");
//    
//    temp[6][4].setText("X");
//    temp[5][5].setText("X");
//
//    temp[5][0].setText("X");
//    temp[4][1].setText("X");  
//    
//    temp[4][5].setText("X");
//    temp[3][6].setText("X"); 
//    
//    temp[0][6].setText("X");     
    return temp;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
