/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.ia.p3.view;

import java.awt.Color;
import javax.swing.JButton;
import uam.ia.p3.main.Aplicacion;

/**
 *
 * @author delta9
 */
public class MainWindow extends javax.swing.JFrame {
    private Aplicacion control;
    private JButton[] buttons;
    private final int ARRAYSIZE = 16;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(Aplicacion app) {
        initComponents();
        this.control = app;
        buttons = new JButton[ARRAYSIZE];
        initButtons();
        configInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(550, 420));

        jPanelTablero.setLayout(new java.awt.GridLayout(4, 4));

        jButton1.setText("Iniciar BFS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Iniciar DFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.iniciarBFS();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        control.iniciarDFS();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void initButtons(){
    int i;

        for(i=0;i<ARRAYSIZE;i++){
            buttons[i] = new JButton("");
            buttons[i].setOpaque(true); //Para poder mostrar el color del boton
            jPanelTablero.add(buttons[i]);
        }
        buttons[0].setBackground(Color.WHITE);
        buttons[2].setBackground(Color.WHITE);
        buttons[5].setBackground(Color.WHITE);
        buttons[7].setBackground(Color.WHITE);
        buttons[8].setBackground(Color.WHITE);
        buttons[10].setBackground(Color.WHITE);
        buttons[13].setBackground(Color.WHITE);
        buttons[15].setBackground(Color.WHITE);
        buttons[1].setBackground(Color.BLACK);
        buttons[3].setBackground(Color.BLACK);
        buttons[4].setBackground(Color.BLACK);
        buttons[6].setBackground(Color.BLACK);
        buttons[9].setBackground(Color.BLACK);
        buttons[11].setBackground(Color.BLACK);
        buttons[12].setBackground(Color.BLACK);
        buttons[14].setBackground(Color.BLACK);
        
    }
    /**
     * @param args the command line arguments
     */

    private void configInicial(){

    buttons[0].setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/ia/p3/view/queenico.jpg"))); 
    buttons[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/ia/p3/view/towerico.jpg"))); 
    buttons[9].setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/ia/p3/view/knight.jpg"))); 
    buttons[12].setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/ia/p3/view/pawnico.jpg"))); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanelTablero;
    // End of variables declaration//GEN-END:variables
}
